<a href="https://colab.research.google.com/github/Inayat2/Pandas/blob/main/AI_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hello computer")

hello computer


In [ ]:
color1, color2, color3= "red", "green", "blue"
color3

'blue'

In [ ]:
x = [1, 2, 3]
y = [1, 2, 3]

print(x is y)     # False
print(x is not y)  # True

False
True


In [ ]:
x= 9
y= 8
print(x<=y)
print(x>y)


False
True


In [ ]:
counter 10


kshivhaeilvhileh

In [ ]:
x = 4       # x is of type int
x = "Sally" # x is now of type str
print(x)


Sally


In [ ]:
if 5 > 2:
  print("Five is greater than two!")


Five is greater than two!


In [ ]:
# prompt: create python calculator

def add(x, y):
  return x + y

def subtract(x, y):
  return x - y

def multiply(x, y):
  return x * y

def divide(x, y):
  return x / y

print("Select operation.")
print("1. Add")
print("2. Subtract")
print("3. Multiply")
print("4. Divide")

while True:
  # Take input from the user
  choice = input("Enter choice (1/2/3/4): ")

  if choice in ('1', '2', '3', '4'):
    num1 = float(input("Enter first number: "))
    num2 = float(input("Enter second number: "))

    if choice == '1':
      result = add(num1, num2)
    elif choice == '2':
      result = subtract(num1, num2)
    elif choice == '3':
      result = multiply(num1, num2)
    elif choice == '4':
      result = divide(num1, num2)

    print(num1, " ", choice, " ", num2, " = ", result)
    break
  else:
    print("Invalid input")


Select operation.
1. Add
2. Subtract
3. Multiply
4. Divide
Enter choice (1/2/3/4): 1
Enter first number: 1
Enter second number: 2
1.0   1   2.0  =  3.0


In [ ]:
x = 5
y = 6
print(x+y)


11


In [ ]:
the_3_drivers = ('qadir dar', 'nab kak', 'gull kak')

In [ ]:
a_candidate = "ab'aziz"

In [ ]:
if a_candidate in the_3_drivers:
print("{} is a drivers".format(a_candidate))
else:
  print("{} is not a drivers".format(a_candidate))

IndentationError: expected an indented block after 'if' statement on line 1 (<ipython-input-5-06e1743da3b5>, line 2)

In [ ]:
if a_candidate in the_3_drivers:
  print("{} is a drivers".format(a_candidate))
else:
  print("{} is not a drivers".format(a_candidate))

ab'aziz is not a drivers


In [ ]:
today = 'december'

In [ ]:
if today == 'november':
  print("today is the day of winter.")

In [ ]:
elif today == 'January':
    print("Today is the day of the moon.")
elif today == 'February':
    print("Today is the day of Tyr, the god of war.")
elif today == 'march':
    print("Today is the day of Odin, the supreme diety.")
elif today == 'april':
    print("Today is the day of Thor, the god of thunder.")
elif today == 'may':
    print("Today is the day of Frigga, the goddess of beauty.")
elif today == 'june':
    print("Today is the day of Saturn, the god of fun and feasting.")

SyntaxError: invalid syntax (<ipython-input-3-9960ff133577>, line 1)

In [ ]:
today = 'September'

In [ ]:
if today == 'January':
    print("Today is the day of the sun.")
elif today == 'March':
    print("Today is the day of the moon.")
elif today == 'April':
    print("Today is the day of Tyr, the god of war.")
elif today == 'November':
    print("Today is the day of Odin, the supreme diety.")
elif today == 'June':
    print("Today is the day of Thor, the god of thunder.")
elif today == 'July':
    print("Today is the day of Frigga, the goddess of beauty.")
elif today == 'September':
    print("Today is the day of Saturn, the god of fun and feasting.")

Today is the day of Saturn, the god of fun and feasting.


In [ ]:
w1, w2, w3, = 0.9, 0.1, 0.5,

In [ ]:
kanto_temp = 73
kanto_rainfall = 67
kanto_humidity = 43

In [ ]:
kanto_yeild_apples = kanto_temp*w1+kanto_rainfall * w2 + kanto_humidity * w3

In [ ]:
kanto_yeild_apples

93.9

In [ ]:
print("the expected value of apple yeild in kanto region is{} per hectare.".format(kanto_yeild_apples))

the expected value of apple yeild in kanto region is93.9 per hectare.


In [ ]:
kupwara = [73, 67, 43]
budgam = [91, 88, 64]
pampore = [87, 134, 58]
suthsoo = [102, 43, 37]
pahroo = [69, 96, 70]

In [ ]:
pahroo

[69, 96, 70]

In [ ]:
for x, w in zip(kupwara, pampore):
  print(x)
  print(w)

73
87
67
134
43
58


In [ ]:
def crop_yield(region, weights):
    result = 0
    for x, w in zip(region, weights):
        result += x * w
    return result

In [ ]:
crop_yield(suthsoo, pampore)

16782

In [ ]:
import numpy as np

arr2 = np.array ([[1, 2, 3, 4],
                  [5, 6, 7, 6],
                  [8, 9, 8, 7]])

In [ ]:
arr2.shape

(3, 4)

In [ ]:
arr4 = np.array([8, 2, 9, 5])

In [ ]:
arr4.shape

(4,)

In [ ]:
arr2 + arr4

array([[ 9,  4, 12,  9],
       [13,  8, 16, 11],
       [16, 11, 17, 12]])

In [ ]:
arr2 * arr4

array([[ 8,  4, 27, 20],
       [40, 12, 63, 30],
       [64, 18, 72, 35]])

In [ ]:
arr5 = np.array([2, 9])

In [ ]:
arr5.shape

(2,)

In [ ]:
arr2+arr5

ValueError: operands could not be broadcast together with shapes (3,4) (2,) 

In [ ]:
import numpy as np

In [ ]:
arr3 = np.array([
    [[11, 12, 13, 14],
     [13, 14, 15, 19]],

    [[15, 16, 17, 21],
     [63, 92, 36, 18]],

    [[98, 32, 81, 23],
     [17, 18, 19.5, 43]]])

In [ ]:
arr3.shape

(3, 2, 4)

In [ ]:
arr3[2,1,2]

19.5

In [ ]:
import numpy as np

In [ ]:
data=np.array([63,  7,  5, 84, 77, 33, 34, 64, 30, 70])

In [ ]:
mean=np.mean(data)

In [ ]:
print(mean)

46.7


In [ ]:
import numpy as np

In [ ]:
r=np.random.randint(1,101,8)
r

array([52, 39, 87, 81, 32, 80, 82, 17])

In [ ]:
mean=np.mean(r)

In [ ]:
mean

58.75

In [ ]:
std_dev=np.std(r)
std_dev

25.44479318053106

In [ ]:
import numpy as np

In [ ]:
arr1=np.array([1,4,6])
arr2=np.array([6,2,2])

In [ ]:
np.dot(arr1,arr2)

26

In [ ]:
heights=np.random.randint(70,80,size=9)

In [ ]:
heights

array([77, 72, 71, 72, 70, 74, 76, 73, 74])

In [ ]:

tallest=np.max(heights)
tallest

77

In [ ]:
heights[heights%2==1]=-1
heights

array([-1, 72, -1, 72, 70, 74, 76, -1, 74])

In [ ]:
heights.reshape(3,3)

array([[-1, 72, -1],
       [72, 70, 74],
       [76, -1, 74]])

In [ ]:
celsius_tempreture=np.array([0,10,20,30,40])

In [ ]:
fahrenheit_tempretures=(celsius_tempreture*9/5)+32
fahrenheit_tempretures

array([ 32.,  50.,  68.,  86., 104.])

In [ ]:
import numpy as np

In [ ]:
heights= np.arange(9).reshape(3,3)

In [ ]:
print("The original array: \n", heights, "\n")

The original array: 
 [[0 1 2]
 [3 4 5]
 [6 7 8]] 



In [ ]:
print("The extracted array:")
print(heights[:,:4])

The extracted array:
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# python code to train pokemon
powers = [3, 8, 9, 7]

mini, maxi = 0, 0

for power in powers:
	if mini == 0 and maxi == 0:
		mini, maxi = powers[0], powers[0]
		print(mini, maxi)
	else:
		mini = min(mini, power)
		maxi = max(maxi, power)
		print(mini, maxi)

# Time Complexity is O(N) with Space Complexity O(1)

3 3
3 8
3 9
3 9


In [ ]:
import numpy as np

In [ ]:
array=[23,65,87,19,]

In [ ]:
array

[23, 65, 87, 19]

In [ ]:
mean=np.mean(array)

In [ ]:
mean

48.5

In [ ]:
arr2=np.array([1,3,5,]),
([6,8,3]),
([9,1,5])


[9, 1, 5]

In [ ]:
arr2.shape

AttributeError: 'tuple' object has no attribute 'shape'